-- ==============================================================================
-- ULTIMATUM PLATFORM - PERFECT FULL MYSQL SEED DATA SET
-- Target: phpMyAdmin (HostGator, cPanel, MariaDB, MySQL 5.6 / 5.7 / 8.0)
-- Description: Clears placeholder rows and populates exact matching profiles,
--              games, recipes, reviews, articles, sponsors, pages, leaderboards.
-- ==============================================================================

-- 1. Disable Foreign Key Checks
SET FOREIGN_KEY_CHECKS = 0;

-- 2. Clear Any Old Placeholder Records (Using DELETE FROM instead of TRUNCATE for MySQL FK safety)
DELETE FROM `bookmarks`;
DELETE FROM `leaderboards`;
DELETE FROM `profiles`;
DELETE FROM `games`;
DELETE FROM `recipes`;
DELETE FROM `reviews`;
DELETE FROM `articles`;
DELETE FROM `sponsors`;
DELETE FROM `pages`;
DELETE FROM `site_settings`;

-- 3. PROFILES
INSERT INTO `profiles` (`id`, `username`, `email`, `role`, `points`, `daily_streak`, `badges`)
VALUES 
    ('user-001', 'PixelNinja', 'admin@ultimatum.gg', 'admin', 4850, 5, '["Grand Champion", "Arcade Master", "Founding Chef", "Super Admin"]'),
    ('user-002', 'CyberGourmet', 'gamer@ultimatum.gg', 'user', 3420, 3, '["Top Gun", "Recipe Critic", "High Roller"]'),
    ('user-003', 'AeroStrike', 'aerostrike@ultimatum.gg', 'user', 2980, 2, '["Sharpshooter", "Speed Demon"]'),
    ('user-004', 'SpiceOverlord', 'spice@ultimatum.gg', 'user', 1840, 1, '["Taste Tester", "Kitchen Samurai"]');

-- 4. GAMES
INSERT INTO `games` (`id`, `slug`, `title`, `description`, `category`, `thumbnail_url`, `game_file_url`, `is_sponsored`, `sponsor_name`, `play_count`)
VALUES
    ('game-001', 'neon-asteroid-blitz', 'Neon Asteroid Blitz', 'High-octane retro arcade shooter. Pilot your neon starship through deep space debris, unleash laser blasts, collect powerup crystals, and dominate the weekly global leaderboard.', 'arcade', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80', 'canvas://neon-asteroid-blitz', 1, 'Razer Gaming Gear', 34820),
    ('game-002', 'cyber-slicer-2099', 'Cyber Slicer 2099', 'Fast-paced rhythmic reflex slicer. Cut glowing energy nodes before they breach your firewall perimeter in this futuristic synthwave challenge.', 'action', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80', 'canvas://cyber-slicer', 0, NULL, 22150),
    ('game-003', 'pixel-kitchen-rush', 'Pixel Kitchen Rush', 'Frenetic 2D culinary rush! Juggle gourmet orders, chop ingredients, flip steaks, and satisfy demanding VIP food critics before the timer expires.', 'puzzle', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80', 'canvas://pixel-kitchen', 1, 'Hestan Masterware', 18940),
    ('game-004', 'dungeon-loot-dash', 'Dungeon Loot Dash', 'Classic 8-bit endless runner. Dodge lava traps, jump over spike barriers, and stack legendary gold chests to redeem exclusive profile badges.', 'retro', 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80', 'canvas://dungeon-loot', 0, NULL, 14780),
    ('game-005', 'sabotage-circuit', 'Sabotage Circuit', '5-Player Asynchronous Deception & Crisis Management Simulator. 4 Engineers must maintain Core Integrity while 1 secretly assigned Saboteur triggers cascading failures across 6 interconnected power and logic sectors.', 'action', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80', 'canvas://sabotage-circuit', 1, 'CyberCore Industries', 28940),
    ('game-006', 'the-architect-and-the-rats', 'The Architect & The Rats', '1v4 Asymmetrical Maze Deception & Escape Arena. 1-2 Architects forge a deadly labyrinth of spikes, decoys, and trigger traps while Rats navigate through fog of war to find the True Gold Exit before time runs out.', 'retro', 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80', 'canvas://the-architect-and-the-rats', 1, 'RetroGrid Labs', 31250);

-- 5. RECIPES
INSERT INTO `recipes` (`id`, `slug`, `title`, `description`, `hero_image_url`, `prep_time`, `cook_time`, `servings`, `calories`, `category`, `cuisine`, `cuisine_tags`, `dietary_tags`, `ingredients`, `instructions`, `nutrition`, `rating`, `rating_count`, `author`)
VALUES
    ('rec-001', 'signature-italian-baked-ziti', 'Signature Italian Baked Ziti with Crispy Basil & Whipped Ricotta', 'An irresistible comfort classic featuring al dente ziti folded into a slow-simmered San Marzano tomato-basil ragù, layered with creamy whipped whole-milk ricotta, and finished under the broiler with crispy golden mozzarella.', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80', 25, 40, 6, 580, 'Pasta & Italian', 'Italian', '["Italian Cuisine", "Mediterranean", "Pasta"]', '["Comfort Food", "Vegetarian Optional", "Crowd Pleaser"]',
    '[{"item": "Ziti or Rigatoni Pasta", "amount": 16, "unit": "oz", "notes": "Cooked 2 mins shy of al dente"}, {"item": "San Marzano Crushed Tomatoes", "amount": 28, "unit": "oz can", "notes": "D.O.P certified"}, {"item": "Whole Milk Ricotta Cheese", "amount": 15, "unit": "oz", "notes": "Whipped with lemon zest"}, {"item": "Fresh Low-Moisture Mozzarella", "amount": 12, "unit": "oz", "notes": "Grated coarsely"}, {"item": "Aged Parmigiano-Reggiano", "amount": 1, "unit": "cup", "notes": "Freshly microplaned"}, {"item": "Extra Virgin Olive Oil", "amount": 3, "unit": "tbsp"}, {"item": "Garlic Cloves", "amount": 5, "unit": "cloves", "notes": "Thinly slivered"}, {"item": "Fresh Genovese Basil Leaves", "amount": 1, "unit": "bunch", "notes": "Torn + fried for garnish"}, {"item": "Crushed Red Pepper Flakes", "amount": 0.5, "unit": "tsp"}, {"item": "Kosher Salt & Fresh Black Pepper", "amount": 1, "unit": "tsp", "notes": "To taste"}]',
    '[{"step": 1, "title": "Par-Cook the Pasta", "instruction": "Bring 4 quarts of heavily salted water to a rolling boil. Drop the ziti and cook for precisely 8 minutes (it should still have a firm center). Drain and toss with 1 tbsp olive oil to prevent sticking."}, {"step": 2, "title": "Simmer the San Marzano Pomodoro", "instruction": "In a heavy Dutch oven, warm 2 tbsp olive oil over medium-low heat. Add slivered garlic and red pepper flakes. Sauté for 90 seconds until fragrant and golden (do not brown). Pour in crushed tomatoes, season with salt and pepper, and simmer for 15 minutes."}, {"step": 3, "title": "Whip the Herb Ricotta", "instruction": "In a medium bowl, whisk together whole milk ricotta, half the grated Parmigiano-Reggiano, fresh cracked black pepper, a pinch of lemon zest, and half of the torn basil until light, fluffy, and cloud-like."}, {"step": 4, "title": "Layer and Assemble", "instruction": "Toss the par-cooked ziti directly into the tomato sauce. Spread half of the pasta mixture into a 9x13-inch baking dish. Dollop generous spoonfuls of the whipped ricotta across the surface. Top with remaining pasta, then blanket completely with shredded mozzarella and remaining Parmigiano."}, {"step": 5, "title": "Bake to Golden Perfection", "instruction": "Bake at 400°F (200°C) for 25 minutes until bubbling vigorously around the edges. Switch the oven to high broil for 3-4 minutes until deep golden brown blister spots form on top. Rest for 10 minutes, garnish with flash-fried basil leaves, and serve."}]',
    '{"calories": 580, "protein": "32g", "carbs": "68g", "fat": "21g", "fiber": "5g"}', 4.9, 342, 'Chef Marco Bellini'),

    ('rec-002', 'triple-layer-chocolate-mocha-fudge-cake', 'Triple-Layer Chocolate Mocha Fudge Cake with Espresso Ganache', 'An ultra-decadent dessert featuring three tiers of dark cocoa sponge infused with freshly pulled espresso, layered with silky whipped dark chocolate fudge, and draped in a mirror-shine espresso ganache drip.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80', 45, 35, 12, 620, 'Desserts & Baking', 'American', '["American Cuisine", "Baking", "Desserts"]', '["Vegetarian", "Indulgent", "Celebration"]',
    '[{"item": "Dutch Processed Dark Cocoa Powder", "amount": 1, "unit": "cup", "notes": "Sifted"}, {"item": "Fresh Hot Espresso / Strong Coffee", "amount": 1.5, "unit": "cups", "notes": "Freshly brewed"}, {"item": "All-Purpose Flour", "amount": 2.5, "unit": "cups"}, {"item": "Granulated Sugar", "amount": 2, "unit": "cups"}, {"item": "Buttermilk", "amount": 1, "unit": "cup", "notes": "Room temperature"}, {"item": "Vegetable or Avocado Oil", "amount": 0.75, "unit": "cup"}, {"item": "Large Eggs", "amount": 3, "unit": "whole", "notes": "Room temperature"}, {"item": "Pure Vanilla Bean Paste", "amount": 1.5, "unit": "tbsp"}, {"item": "Baking Powder & Baking Soda", "amount": 1.5, "unit": "tsp each"}, {"item": "70% Dark Bittersweet Chocolate", "amount": 14, "unit": "oz", "notes": "Finely chopped for ganache"}, {"item": "Heavy Whipping Cream", "amount": 1.5, "unit": "cups", "notes": "For ganache & frosting"}, {"item": "Flaky Maldon Sea Salt", "amount": 1, "unit": "tsp", "notes": "For finishing"}]',
    '[{"step": 1, "title": "Bloom Cocoa in Hot Espresso", "instruction": "In a heatproof bowl, whisk the dark cocoa powder directly into the piping-hot freshly pulled espresso. Let bloom for 5 minutes to activate deep chocolate aromatics."}, {"step": 2, "title": "Mix the Batter", "instruction": "Whisk dry ingredients in a large stand mixer bowl. In a separate pitcher, whisk buttermilk, oil, eggs, and vanilla. Pour wet mixture into dry, followed by the warm espresso-cocoa elixir on low speed until glossy."}, {"step": 3, "title": "Bake Three Sponge Rounds", "instruction": "Divide batter evenly between three 8-inch cake pans. Bake at 350°F (175°C) for 30-35 minutes until a toothpick comes out clean. Cool completely on wire racks."}, {"step": 4, "title": "Prepare Velvet Espresso Ganache", "instruction": "Heat heavy cream until simmering. Pour over chopped dark chocolate, let rest 3 minutes, then whisk from the center outward until smooth."}, {"step": 5, "title": "Stack, Frost, and Chill", "instruction": "Stack layers with whipped fudge filling. Pour luscious espresso ganache over top, letting dramatic drips cascade down the sides."}]',
    '{"calories": 620, "protein": "9g", "carbs": "74g", "fat": "34g", "fiber": "7g"}', 5.0, 512, 'Pastry Chef Elena Vance'),

    ('rec-003', 'crispy-garlic-butter-salmon-bowls', 'Crispy Garlic Butter Salmon Bowls with Avocado & Sticky Rice', 'Crisp, caramelized pan-seared salmon cubes glazed in a soy-garlic honey butter, served over warm jasmine rice with sliced avocado, pickled cucumbers, and spicy sriracha mayo.', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80', 15, 15, 4, 520, 'Seafood & Bowls', 'Japanese', '["Japanese Cuisine", "Asian Fusion", "Seafood"]', '["High Protein", "Gluten-Free Optional", "Quick Dinner"]',
    '[{"item": "Fresh Atlantic Salmon Fillet", "amount": 1.5, "unit": "lbs", "notes": "Cut into 1-inch bite-sized cubes"}, {"item": "Unsalted Grass-Fed Butter", "amount": 3, "unit": "tbsp"}, {"item": "Garlic Cloves", "amount": 4, "unit": "cloves", "notes": "Minced"}, {"item": "Low-Sodium Tamari / Soy Sauce", "amount": 2, "unit": "tbsp"}, {"item": "Wild Blossom Honey", "amount": 1.5, "unit": "tbsp"}, {"item": "Cooked Jasmine Rice", "amount": 3, "unit": "cups"}, {"item": "Ripe Haas Avocados", "amount": 2, "unit": "whole"}, {"item": "Persian Cucumbers", "amount": 2, "unit": "whole"}, {"item": "Toasted Sesame Oil & Seeds", "amount": 1, "unit": "tbsp"}, {"item": "Sriracha Mayo Drizzle", "amount": 2, "unit": "tbsp"}]',
    '[{"step": 1, "title": "Prep Salmon Cubes", "instruction": "Pat salmon cubes dry. Season with sea salt, black pepper, and garlic powder."}, {"step": 2, "title": "Pan-Sear for Golden Crust", "instruction": "Sear salmon in a hot cast-iron skillet for 2-3 minutes per side until golden and crispy."}, {"step": 3, "title": "Glaze with Garlic Butter", "instruction": "Add butter, garlic, soy sauce, and honey. Baste sizzling glaze over salmon for 60 seconds."}, {"step": 4, "title": "Assemble Nourishing Bowls", "instruction": "Divide warm jasmine rice into bowls. Top with glazed salmon, avocado, pickled cucumbers, and sriracha mayo."}]',
    '{"calories": 520, "protein": "42g", "carbs": "48g", "fat": "18g", "fiber": "4g"}', 4.8, 215, 'Chef Marco Bellini'),

    ('rec-004', 'truffle-butter-ribeye-steak', 'Dry-Aged Ribeye Steak with Black Truffle Compound Butter & Charred Asparagus', 'A 45-day dry-aged prime ribeye seared in cast iron with foaming rosemary-garlic butter, finished with an earthy black truffle compound butter medallion and charred lemon-parmesan asparagus spears.', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80', 15, 12, 2, 690, 'Steakhouse & Grills', 'American', '["American Cuisine", "Steakhouse", "Gourmet"]', '["High Protein", "Keto Friendly", "Gourmet"]',
    '[{"item": "Dry-Aged USDA Prime Ribeye (1.5-inch thick)", "amount": 2, "unit": "steaks (16 oz ea)", "notes": "Brought to room temperature"}, {"item": "European High-Fat Unsalted Butter", "amount": 4, "unit": "tbsp", "notes": "Divided for searing & compound butter"}, {"item": "Black Truffle Pate / Minced Truffles", "amount": 1.5, "unit": "tbsp"}, {"item": "Fresh Rosemary Sprigs", "amount": 3, "unit": "sprigs"}, {"item": "Fresh Thyme Sprigs", "amount": 4, "unit": "sprigs"}, {"item": "Garlic Cloves", "amount": 6, "unit": "cloves", "notes": "Lightly crushed with skin on"}, {"item": "Fresh Asparagus", "amount": 1, "unit": "bunch", "notes": "Woody ends trimmed"}, {"item": "Flaky Maldon Smoked Sea Salt", "amount": 1, "unit": "tbsp"}, {"item": "Coarsely Cracked Black Peppercorns", "amount": 1, "unit": "tbsp"}, {"item": "Aged Parmigiano-Reggiano", "amount": 2, "unit": "tbsp", "notes": "Shaved over asparagus"}, {"item": "Fresh Lemon Juice", "amount": 1, "unit": "tbsp"}]',
    '[{"step": 1, "title": "Compound Butter Preparation", "instruction": "Mix softened European butter, minced black truffle, a pinch of sea salt, and minced thyme in a small bowl. Roll into a log using parchment paper and chill in the freezer for 15 minutes to firm up."}, {"step": 2, "title": "Dry Brine & Season Steaks", "instruction": "Pat ribeye steaks thoroughly dry with paper towels. Season generously on all sides and edges with flaky smoked sea salt and cracked black pepper."}, {"step": 3, "title": "Cast-Iron Hard Sear", "instruction": "Heat a heavy cast-iron skillet over high heat until lightly smoking. Add 1 tbsp avocado oil, then lay the steaks in gently. Sear undisturbed for 2 minutes per side to develop a deep Maillard crust."}, {"step": 4, "title": "Aromatics & Butter Basting (Arrosé)", "instruction": "Lower heat to medium. Drop in 2 tbsp butter, crushed garlic, thyme, and rosemary. Tilt the pan and continuously spoon the foaming aromatic butter over the steaks for 2-3 minutes until internal temperature hits 130°F (54°C) for medium-rare."}, {"step": 5, "title": "Rest & Char Asparagus", "instruction": "Transfer steaks to a cutting board and top each with a thick medallion of truffle butter; rest for 8 minutes. In the remaining pan drippings, flash-sear the asparagus for 3 minutes. Finish with lemon juice and shaved Parmigiano before serving alongside sliced steak."}]',
    '{"calories": 690, "protein": "58g", "carbs": "6g", "fat": "48g", "fiber": "3g"}', 4.95, 428, 'Chef Marco Bellini'),

    ('rec-005', 'artisan-margherita-pizza-napoletana', '72-Hour Fermented Neapolitan Pizza Margherita with Fior di Latte', 'Authentic wood-fired style pizza featuring a 72-hour cold-fermented high-hydration dough with blistered leopard spotting, crushed San Marzano D.O.P. sauce, torn fresh fior di latte mozzarella, and cold-pressed olive oil.', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80', 30, 8, 4, 480, 'Artisanal Pizzas & Breads', 'Italian', '["Italian Cuisine", "Neapolitan", "Pizza"]', '["Comfort Food", "Vegetarian Optional", "Crowd Pleaser"]',
    '[{"item": "Tipo 00 Italian Pizza Flour", "amount": 500, "unit": "g"}, {"item": "Cold Filtered Water (65% hydration)", "amount": 325, "unit": "ml"}, {"item": "Fine Sea Salt", "amount": 15, "unit": "g"}, {"item": "Instant Dry Yeast", "amount": 1.5, "unit": "g"}, {"item": "San Marzano D.O.P. Whole Peeled Tomatoes", "amount": 14, "unit": "oz can", "notes": "Hand-crushed with salt"}, {"item": "Fresh Fior di Latte Mozzarella", "amount": 250, "unit": "g", "notes": "Drained and torn"}, {"item": "Fresh Genovese Basil Leaves", "amount": 16, "unit": "leaves"}, {"item": "Extra Virgin Olive Oil (Cold Pressed)", "amount": 2, "unit": "tbsp"}, {"item": "Semolina Flour", "amount": 0.25, "unit": "cup", "notes": "For dusting peel"}]',
    '[{"step": 1, "title": "72-Hour Cold Fermentation Dough", "instruction": "Mix flour, water, yeast, and salt until smooth. Bulk ferment for 2 hours at room temperature, fold into 4 tight dough balls (210g each), and cold-proof in airtight containers in the refrigerator for 48 to 72 hours."}, {"step": 2, "title": "Hand-Crush Sauce & Drain Cheese", "instruction": "Hand-crush San Marzano tomatoes with a pinch of sea salt (do not blend to avoid seeds bittering). Tear fior di latte into bite-sized pieces and let drain on paper towels for 30 minutes to prevent soggy crust."}, {"step": 3, "title": "Oven & Pizza Stone Preheating", "instruction": "Preheat oven with a pizza steel or stone on the top rack at maximum heat (500°F - 550°F / 260°C - 290°C) for at least 60 minutes."}, {"step": 4, "title": "Shape Dough & Assemble", "instruction": "Dust work surface with semolina. Gently stretch a dough ball from the center outward, preserving the airy outer cornicione rim. Spread 3 tbsp tomato sauce, arrange torn mozzarella, and drizzle extra virgin olive oil."}, {"step": 5, "title": "Bake to Leopard Blistered Perfection", "instruction": "Switch oven to high broil. Launch pizza onto the blazing steel. Bake for 5-7 minutes until the crust exhibits charred leopard spots and cheese is bubbling vigorously. Garnish immediately with fresh basil leaves and a final olive oil swirl."}]',
    '{"calories": 480, "protein": "22g", "carbs": "64g", "fat": "15g", "fiber": "4g"}', 4.9, 389, 'Chef Marco Bellini'),

    ('rec-006', 'smoky-birria-beef-tacos', 'Slow-Braised Jalisco Beef Birria Quesa-Tacos with Rich Consomé', 'Tender beef chuck and short ribs slow-braised for 4 hours in a rich Guajillo and Ancho chili broth, shredded and folded into corn tortillas dipped in spiced chili oil, griddled with Oaxaca cheese, and served with steaming cilantro consomé.', 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80', 30, 240, 6, 560, 'Mexican & Street Food', 'Mexican', '["Mexican Cuisine", "Street Food", "Tacos"]', '["Comfort Food", "High Protein", "Crowd Pleaser"]',
    '[{"item": "Beef Chuck Roast & Bone-In Short Ribs", "amount": 3.5, "unit": "lbs", "notes": "Cut into large chunks"}, {"item": "Dried Guajillo Chiles", "amount": 6, "unit": "whole", "notes": "Stemmed and deseeded"}, {"item": "Dried Ancho Chiles", "amount": 3, "unit": "whole", "notes": "Stemmed and deseeded"}, {"item": "Dried Chiles de Árbol", "amount": 2, "unit": "whole", "notes": "For gentle heat"}, {"item": "White Onion & Garlic Head", "amount": 1, "unit": "each", "notes": "Halved onion + 8 peeled garlic cloves"}, {"item": "Mexican Cinnamon Stick (Canela)", "amount": 1, "unit": "stick"}, {"item": "Mexican Oregano & Ground Cumin", "amount": 1, "unit": "tbsp each"}, {"item": "Apple Cider Vinegar", "amount": 0.25, "unit": "cup"}, {"item": "Beef Bone Broth", "amount": 4, "unit": "cups"}, {"item": "Yellow Corn Tortillas", "amount": 18, "unit": "count"}, {"item": "Oaxaca Cheese or Quesadilla Cheese", "amount": 12, "unit": "oz", "notes": "Shredded"}, {"item": "Fresh Cilantro & Diced White Onion", "amount": 1, "unit": "cup", "notes": "For garnish and dipping cup"}, {"item": "Fresh Limes", "amount": 3, "unit": "whole", "notes": "Cut into wedges"}]',
    '[{"step": 1, "title": "Toast & Rehydrate Dried Chilies", "instruction": "Toast dried guajillo, ancho, and árbol chilies in a dry Dutch oven for 60 seconds until fragrant. Cover with hot water and soak for 15 minutes until softened."}, {"step": 2, "title": "Blend the Adobo Marinade", "instruction": "Transfer softened chilies to a high-speed blender with vinegar, garlic cloves, onion, Mexican oregano, cumin, cinnamon, black pepper, and 1 cup of beef broth. Blend until silky smooth."}, {"step": 3, "title": "Slow-Braise Beef to Fall-Apart Tenderness", "instruction": "Season beef heavily with salt. Sear in the Dutch oven until browned. Strain chili adobo over the meat and add remaining beef broth. Cover tightly and simmer on low heat (or 325°F oven) for 3.5 to 4 hours until meltingly tender."}, {"step": 4, "title": "Shred Meat & Skim Consomé Oil", "instruction": "Shred the succulent beef and discard bones. Skim the rich spiced red oil from the surface of the consomé into a wide bowl. Season the broth with lime juice and salt."}, {"step": 5, "title": "Griddle Quesa-Tacos & Serve with Dipping Consomé", "instruction": "Dip corn tortillas into the skimmed chili oil, place on a hot flat-top griddle. Top with shredded Oaxaca cheese and beef. Fold in half and fry until deeply golden and crispy. Serve piping hot with mugs of chopped cilantro-onion consomé for dipping."}]',
    '{"calories": 560, "protein": "38g", "carbs": "34g", "fat": "31g", "fiber": "6g"}', 4.98, 620, 'Chef Sophia Rossi'),

    ('rec-007', 'creamy-tuscan-garlic-chicken', 'Pan-Seared Creamy Tuscan Garlic Chicken with Sun-Dried Tomatoes & Spinach', 'Golden herb-crusted chicken cutlets swimming in a velvety parmesan and garlic cream sauce laced with tart sun-dried tomatoes, wilted baby spinach, and fresh basil ribbons.', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80', 10, 20, 4, 490, 'Poultry & Mains', 'Italian', '["Italian Cuisine", "Tuscan", "Poultry"]', '["High Protein", "Keto Friendly", "Quick Dinner"]',
    '[{"item": "Boneless Skinless Chicken Breasts", "amount": 2, "unit": "large (1.5 lbs)", "notes": "Sliced horizontally into 4 thin cutlets"}, {"item": "Italian Herb Seasoning & Smoked Paprika", "amount": 1, "unit": "tbsp"}, {"item": "Extra Virgin Olive Oil", "amount": 2, "unit": "tbsp"}, {"item": "Unsalted Butter", "amount": 2, "unit": "tbsp"}, {"item": "Garlic Cloves", "amount": 6, "unit": "cloves", "notes": "Finely minced"}, {"item": "Oil-Packed Sun-Dried Tomatoes", "amount": 0.5, "unit": "cup", "notes": "Drained and julienned"}, {"item": "Heavy Cream", "amount": 1, "unit": "cup"}, {"item": "Low-Sodium Chicken Bone Broth", "amount": 0.5, "unit": "cup"}, {"item": "Aged Parmigiano-Reggiano", "amount": 0.75, "unit": "cup", "notes": "Freshly grated"}, {"item": "Fresh Baby Spinach Leaves", "amount": 3, "unit": "cups", "notes": "Packed"}, {"item": "Fresh Basil Ribbons", "amount": 0.25, "unit": "cup"}]',
    '[{"step": 1, "title": "Season & Sear Chicken Cutlets", "instruction": "Pat chicken dry. Season with salt, pepper, Italian herbs, and paprika. Heat olive oil and 1 tbsp butter in a 12-inch skillet over medium-high heat. Sear cutlets for 4-5 minutes per side until golden and cooked to 165°F. Transfer to a plate."}, {"step": 2, "title": "Sauté Garlic & Sun-Dried Tomatoes", "instruction": "Melt remaining butter in the same skillet. Add minced garlic and sun-dried tomatoes; sauté for 60 seconds until delightfully fragrant."}, {"step": 3, "title": "Simmer Cream & Parmesan Velouté", "instruction": "Pour in chicken broth to deglaze pan browned bits. Stir in heavy cream and bring to a gentle simmer. Reduce heat to low, whisk in grated Parmigiano until silky smooth and slightly thickened."}, {"step": 4, "title": "Fold Spinach & Return Chicken", "instruction": "Add fresh baby spinach and stir until gently wilted (about 2 minutes). Return golden chicken cutlets and resting juices back to the skillet, spooning the luxurious cream sauce over the meat."}, {"step": 5, "title": "Garnish & Serve", "instruction": "Garnish with fresh basil ribbons and cracked black pepper. Serve immediately over buttered fettuccine, cauliflower mash, or crusty ciabatta."}]',
    '{"calories": 490, "protein": "46g", "carbs": "11g", "fat": "28g", "fiber": "3g"}', 4.88, 275, 'Chef Marco Bellini'),

    ('rec-008', 'matcha-green-tea-tiramisu', 'Ceremonial Uji Matcha Tiramisu with Whipped Mascarpone & Yuzu Kiss', 'A modern Japanese-Italian fusion dessert crafted with sponge ladyfingers drenched in ceremonial grade Uji matcha liquor, layered with cloud-like yuzu mascarpone cream, and dusted with emerald matcha velvet.', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1200&q=80', 35, 0, 8, 410, 'Desserts & Baking', 'Japanese', '["Japanese Cuisine", "Fusion", "Desserts"]', '["Desserts", "Vegetarian", "Indulgent"]',
    '[{"item": "Ceremonial Grade Uji Matcha Powder", "amount": 3, "unit": "tbsp", "notes": "Sifted (divided for soaking & dusting)"}, {"item": "Warm Water (175°F / 80°C)", "amount": 1.5, "unit": "cups"}, {"item": "Italian Savoiardi Ladyfingers", "amount": 24, "unit": "cookies"}, {"item": "Authentic Mascarpone Cheese", "amount": 16, "unit": "oz (450g)", "notes": "Room temperature"}, {"item": "Heavy Whipping Cream (36% fat)", "amount": 1.25, "unit": "cups", "notes": "Chilled"}, {"item": "Granulated Sugar", "amount": 0.75, "unit": "cup"}, {"item": "Pasteurized Egg Yolks", "amount": 3, "unit": "large"}, {"item": "Fresh Yuzu Juice or Lemon Zest", "amount": 1, "unit": "tsp", "notes": "For subtle citrus lift"}, {"item": "Mirin or Sweet White Rum (Optional)", "amount": 1, "unit": "tbsp"}]',
    '[{"step": 1, "title": "Whisk Matcha Soaking Elixir", "instruction": "In a shallow dish, whisk 2 tbsp sifted ceremonial matcha powder with warm water, 2 tbsp sugar, and optional rum using a bamboo chasen whisk until smooth and frothy. Allow to cool."}, {"step": 2, "title": "Whip Sabayon & Creamy Mascarpone", "instruction": "Whisk egg yolks with remaining sugar over a gentle double boiler for 4-5 minutes until pale and doubled in volume. Whisk in mascarpone and yuzu juice until glossy and uniform."}, {"step": 3, "title": "Fold Whipped Cream for Cloud Texture", "instruction": "In a chilled bowl, beat heavy whipping cream to medium-stiff peaks. Gently fold whipped cream into the mascarpone mixture in three additions with a rubber spatula."}, {"step": 4, "title": "Dip Ladyfingers & Layer Dish", "instruction": "Quickly submerge each ladyfinger in the matcha tea for 1-2 seconds (do not over-soak). Line the bottom of an 8x8-inch glass dish. Spread half the mascarpone cream. Repeat with a second layer of soaked ladyfingers and finish with remaining cream smoothed flat."}, {"step": 5, "title": "Chill & Velvet Matcha Dusting", "instruction": "Refrigerate uncovered for at least 6 hours (or overnight) to set. Right before presenting, generously dust the top with remaining ceremonial matcha powder using a fine sieve for a pristine emerald finish."}]',
    '{"calories": 410, "protein": "8g", "carbs": "42g", "fat": "23g", "fiber": "2g"}', 4.92, 310, 'Pastry Chef Elena Vance'),

    ('rec-009', 'shoyu-ramen-with-chashu-pork', 'Kyoto-Style Shoyu Ramen with 12-Hour Chashu Pork Belly & Ajitsuke Tamago', 'Silky clear chicken-dashi broth infused with aged smoked soy tare, springy hand-folded alkaline noodles, melt-in-the-mouth rolled pork chashu, jammy marinated eggs, and fragrant scallion oil.', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80', 40, 180, 4, 640, 'Asian & Stir-Fry', 'Japanese', '["Japanese Cuisine", "Ramen", "Noodles"]', '["Comfort Food", "High Protein", "Gourmet"]',
    '[{"item": "Fresh Alkaline Ramen Noodles", "amount": 4, "unit": "portions (600g)"}, {"item": "Pork Belly (Skin-on or off)", "amount": 2, "unit": "lbs", "notes": "Rolled and tied with butcher twine"}, {"item": "Japanese Shoyu (Aged Soy Sauce)", "amount": 0.75, "unit": "cup"}, {"item": "Mirin & Japanese Sake", "amount": 0.5, "unit": "cup each"}, {"item": "Kombu Kelp & Katsuobushi (Bonito Flakes)", "amount": 1, "unit": "sheet + 1 cup flakes", "notes": "For dashi base"}, {"item": "Rich Chicken Stock", "amount": 6, "unit": "cups"}, {"item": "Large Eggs (Soft-boiled 6 min 30 sec)", "amount": 4, "unit": "whole", "notes": "Marinated in tare"}, {"item": "Scallions / Green Onions", "amount": 6, "unit": "stalks", "notes": "Thinly sliced"}, {"item": "Seasoned Menma (Bamboo Shoots)", "amount": 0.5, "unit": "cup"}, {"item": "Toasted Nori Seaweed Sheets", "amount": 4, "unit": "sheets"}, {"item": "Aromatic Scallion Oil / Rayu", "amount": 2, "unit": "tbsp"}]',
    '[{"step": 1, "title": "Braise Chashu Pork Belly", "instruction": "Sear rolled pork belly in a Dutch oven until golden on all sides. Add soy sauce, mirin, sake, water, scallion whites, and ginger. Simmer on low covered for 2 hours until tender. Chill pork before slicing into neat 1/4-inch rounds."}, {"step": 2, "title": "Marinate Jammy Ajitsuke Eggs", "instruction": "Boil eggs for exactly 6 minutes and 30 seconds, plunge into ice water and peel carefully. Submerge in 1/2 cup of cooled chashu braising liquid for 4 to 12 hours."}, {"step": 3, "title": "Simmer Double-Soup Broth & Tare", "instruction": "Steep kombu kelp and bonito flakes in hot chicken stock for 20 minutes; strain to create a pristine dashi-chicken double broth. Keep at a rolling simmer."}, {"step": 4, "title": "Boil Fresh Noodles", "instruction": "Boil fresh alkaline ramen noodles in a large pot of unsalted boiling water for 90 seconds (firm bite). Shake noodles thoroughly in a strainer to remove excess moisture."}, {"step": 5, "title": "Bowl Assembly & Torch Garnish", "instruction": "In 4 pre-warmed ramen bowls, add 2 tbsp smoked shoyu tare and 1 tsp scallion oil. Ladle 1.5 cups piping hot broth and whisk. Fold noodles in. Top with torched chashu slices, halved jammy egg, menma, scallions, and nori sheets."}]',
    '{"calories": 640, "protein": "36g", "carbs": "68g", "fat": "26g", "fiber": "4g"}', 4.96, 480, 'Chef Kenji Takahashi'),

    ('rec-010', 'avocado-poached-egg-sourdough-toast', 'Artisanal Sourdough Avocado Toast with Poached Eggs, Pickled Shallots & Dukkah', 'Charred rustic sourdough lathered with citrus-smashed Hass avocados, perfectly poached organic eggs with runny yolks, crunchy Egyptian dukkah spice blend, microgreens, and pickled shallot rings.', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80', 10, 5, 2, 380, 'Breakfast & Brunch', 'Mediterranean', '["Mediterranean", "Brunch", "Healthy"]', '["Vegetarian Optional", "High Protein", "Quick Dinner"]',
    '[{"item": "Artisanal Country Sourdough Bread", "amount": 2, "unit": "thick slices"}, {"item": "Ripe Hass Avocados", "amount": 2, "unit": "whole"}, {"item": "Fresh Organic Large Eggs", "amount": 2, "unit": "whole"}, {"item": "Egyptian Dukkah (Toasted Hazelnuts, Sesame, Coriander, Cumin)", "amount": 2, "unit": "tbsp"}, {"item": "Pickled Red Shallot Rings", "amount": 2, "unit": "tbsp"}, {"item": "Fresh Lime Juice", "amount": 1, "unit": "tbsp"}, {"item": "Extra Virgin Olive Oil", "amount": 1, "unit": "tbsp"}, {"item": "Garlic Clove", "amount": 1, "unit": "clove", "notes": "Cut in half for rubbing bread"}, {"item": "Organic Pea Shoots or Radish Microgreens", "amount": 0.5, "unit": "cup"}, {"item": "Flaky Pink Himalayan Salt & Aleppo Pepper", "amount": 0.5, "unit": "tsp each"}]',
    '[{"step": 1, "title": "Toast & Garlic-Rub Sourdough", "instruction": "Brush thick slices of sourdough with olive oil and toast on a hot cast-iron skillet until deeply golden with charred edges. Lightly rub cut garlic clove across the warm crusty surface."}, {"step": 2, "title": "Citrus Herb Avocado Smash", "instruction": "Scoop ripe avocados into a bowl. Add fresh lime juice, flaky sea salt, black pepper, and a drizzle of olive oil. Coarsely mash with a fork, leaving satisfying chunks."}, {"step": 3, "title": "Poach Eggs to Silky Yolk Perfection", "instruction": "Bring a pot of water to a gentle sub-boil (190°F) with 1 tbsp white vinegar. Create a gentle whirlpool, drop cracked egg into the center, and poach for precisely 3 minutes. Remove with a slotted spoon and drain on paper towel."}, {"step": 4, "title": "Assemble with Crunch & Color", "instruction": "Generously spread chunky smashed avocado over the toasted sourdough. Crown each slice with a warm poached egg."}, {"step": 5, "title": "Finishing Touches", "instruction": "Scatter crunchy hazelnut dukkah spice, tangy pickled shallot rings, fresh microgreens, and a dusting of Aleppo pepper flakes. Slice open the egg yolk to cascade down the avocado."}]',
    '{"calories": 380, "protein": "18g", "carbs": "32g", "fat": "22g", "fiber": "8g"}', 4.85, 194, 'Chef Sophia Rossi'),

    ('rec-011', 'velvety-butter-chicken-murgh-makhani', 'Restaurant-Grade Velvety Butter Chicken (Murgh Makhani) with Kasuri Methi', 'Smoky, charred tandoori-marinated chicken thighs simmered in a velvety silk gravy of San Marzano tomatoes, cashew butter, double cream, and crushed sun-dried fenugreek leaves (kasuri methi).', 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=1200&q=80', 25, 35, 5, 590, 'Curries & Stews', 'Indian', '["Indian Cuisine", "North Indian", "Curry", "Mughlai"]', '["High Protein", "Gluten-Free", "Comfort Food", "Crowd Pleaser"]',
    '[{"item": "Boneless Skinless Chicken Thighs", "amount": 2, "unit": "lbs", "notes": "Cut into bite-sized chunks"}, {"item": "Greek Yogurt / Hung Curd", "amount": 0.5, "unit": "cup", "notes": "For tandoori marinade"}, {"item": "Garlic-Ginger Paste", "amount": 2.5, "unit": "tbsp", "notes": "Freshly pounded"}, {"item": "Kashmiri Red Chili Powder", "amount": 2, "unit": "tbsp", "notes": "Vibrant color and mild heat"}, {"item": "Garam Masala & Ground Cumin", "amount": 1.5, "unit": "tbsp each"}, {"item": "Ripe Plum / San Marzano Tomatoes", "amount": 24, "unit": "oz", "notes": "Blanched and pureed smooth"}, {"item": "Raw Cashew Nuts", "amount": 0.33, "unit": "cup", "notes": "Soaked in hot water and blended smooth"}, {"item": "Grass-Fed Butter", "amount": 4, "unit": "tbsp", "notes": "Divided"}, {"item": "Heavy Double Cream", "amount": 0.5, "unit": "cup"}, {"item": "Kasuri Methi (Dried Fenugreek Leaves)", "amount": 1.5, "unit": "tbsp", "notes": "Toasted and crushed between palms"}, {"item": "Honey or Jaggery", "amount": 1, "unit": "tbsp", "notes": "To balance acidity"}, {"item": "Fresh Cilantro", "amount": 0.25, "unit": "cup", "notes": "Finely chopped for garnish"}]',
    '[{"step": 1, "title": "Tandoori Chicken Marinade", "instruction": "In a bowl, mix chicken with Greek yogurt, 1 tbsp ginger-garlic paste, 1 tbsp Kashmiri chili, 1 tsp garam masala, lemon juice, and 1 tsp salt. Marinate for at least 30 minutes (or overnight)."}, {"step": 2, "title": "High-Heat Charring", "instruction": "Heat 1 tbsp butter in a cast-iron skillet or broil chicken on high rack for 8-10 minutes until edges develop deep smoky tandoori char spots. Remove and set aside."}, {"step": 3, "title": "Build the Makhani Velouté", "instruction": "Melt 2 tbsp butter in a heavy saucepot. Sauté remaining ginger-garlic paste for 60 seconds. Pour in pureed tomatoes, Kashmiri chili, cumin, and salt. Simmer covered on medium-low for 15 minutes until oil separates."}, {"step": 4, "title": "Silk Cashew Emulsion & Cream", "instruction": "Pour the blended cashew paste and simmer for 5 minutes until creamy. Strain gravy through a fine-mesh sieve if restaurant-mirror silkiness is desired. Stir in heavy cream and honey."}, {"step": 5, "title": "Simmer Chicken & Fenugreek Aromatics", "instruction": "Fold charred chicken into the velvety sauce along with resting juices. Simmer for 7 minutes on low. Finish with remaining butter and crush toasted kasuri methi over top. Garnish with cream swirl and fresh cilantro."}]',
    '{"calories": 590, "protein": "44g", "carbs": "14g", "fat": "38g", "fiber": "4g"}', 4.97, 512, 'Chef Rajesh Sharma & Ultimatum Test Kitchen'),

    ('rec-012', 'authentic-lahori-mutton-karahi', 'Authentic Lahori Mutton Karahi with Fresh Ginger Juliennes & Green Chilies', 'A legendary Desi specialty cooked in an authentic iron wok on blazing high flame. Tender bone-in goat/lamb braised in fresh tomatoes, garlic, freshly ground black peppercorns, roasted cumin, and pungent green chilies with zero onion filler.', 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=1200&q=80', 20, 55, 4, 610, 'Curries & Stews', 'Desi', '["Desi Cuisine", "Pakistani", "Lahori", "Karahi", "Mutton"]', '["High Protein", "Keto Friendly", "Gluten-Free", "Spicy"]',
    '[{"item": "Bone-In Mutton or Young Goat/Lamb", "amount": 2, "unit": "lbs", "notes": "Cut into 1.5-inch curry pieces"}, {"item": "Fresh Red Tomatoes", "amount": 6, "unit": "large", "notes": "Halved lengthwise"}, {"item": "Fresh Ginger", "amount": 3, "unit": "inch knobs", "notes": "Divided: half crushed paste, half thin juliennes"}, {"item": "Fresh Garlic Cloves", "amount": 10, "unit": "cloves", "notes": "Crushed with coarse salt"}, {"item": "Desi Ghee or Mustard Oil", "amount": 0.33, "unit": "cup"}, {"item": "Fresh Green Birds-Eye Chilies", "amount": 6, "unit": "whole", "notes": "Slit lengthwise"}, {"item": "Coarsely Crushed Black Peppercorns", "amount": 1.5, "unit": "tbsp", "notes": "Freshly mortar-pestle cracked"}, {"item": "Roasted Coriander & Cumin Seeds", "amount": 1.5, "unit": "tbsp", "notes": "Dry roasted and coarsely cracked"}, {"item": "Whisked Greek Yogurt", "amount": 3, "unit": "tbsp"}, {"item": "Fresh Cilantro", "amount": 0.5, "unit": "cup", "notes": "Generously chopped"}, {"item": "Fresh Lemon Juice", "amount": 1.5, "unit": "tbsp"}]',
    '[{"step": 1, "title": "Initial Meat Braise in Wok (Karahi)", "instruction": "In a traditional cast-iron wok (karahi), add mutton, crushed garlic paste, half the ginger paste, 1 cup water, and 1 tsp salt. Cover tightly and simmer on medium-low for 35-40 minutes until meat is 80% tender."}, {"step": 2, "title": "Layer Halved Tomatoes", "instruction": "Uncover wok and arrange halved tomatoes cut-side down directly over the simmering meat. Cover for 7 minutes until skins loosen. Use kitchen tongs to peel off and discard all tomato skins, then mash the pulp into the juices with a flat spatula."}, {"step": 3, "title": "High-Flame Desi Bhunai (Sear)", "instruction": "Turn the burner to high heat. Add desi ghee, slit green chilies, and whisked yogurt. Stir vigorously for 8-10 minutes (bhunai technique) until water evaporates and fragrant red-gold ghee separates around the rim."}, {"step": 4, "title": "Add Fresh Aromatics & Roasted Spices", "instruction": "Sprinkle freshly crushed black peppercorns, roasted coriander-cumin powder, and garam masala. Toss for 90 seconds to lock in aromas without scorching spices."}, {"step": 5, "title": "Garnish & Sizzling Presentation", "instruction": "Remove from flame. Generously heap fresh ginger juliennes, chopped cilantro, and fresh lemon juice over the bubbling karahi. Serve sizzling hot directly in the wok with tandoori roghani naan."}]',
    '{"calories": 610, "protein": "48g", "carbs": "9g", "fat": "42g", "fiber": "3g"}', 4.99, 488, 'Chef Tariq Lahori & Ultimatum Test Kitchen'),

    ('rec-013', 'royal-hyderabadi-mutton-dum-biryani', 'Royal Hyderabadi Mutton Dum Biryani with Saffron Milk & Caramelized Onions', 'The pinnacle of royal Mughlai-Deccani cuisine. Marinated bone-in mutton par-cooked with aromatic whole spices, layered with 70% par-boiled aged long-grain basmati rice, fried crisp shallots (birista), saffron-infused warm milk, and sealed with dough for authentic steam dum cooking.', 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80', 40, 60, 8, 670, 'Curries & Stews', 'Desi', '["Desi Cuisine", "Indian Cuisine", "Biryani", "Hyderabadi", "Rice"]', '["High Protein", "Comfort Food", "Celebration", "Crowd Pleaser"]',
    '[{"item": "Aged Extra-Long Basmati Rice (2+ Years Aged)", "amount": 3.5, "unit": "cups (700g)", "notes": "Washed and soaked for 45 mins"}, {"item": "Bone-In Tender Mutton / Goat", "amount": 2.5, "unit": "lbs", "notes": "Cut into medium pieces"}, {"item": "Golden Fried Crispy Onions (Birista)", "amount": 2, "unit": "cups", "notes": "Thinly sliced and golden fried"}, {"item": "Thick Whole Milk Yogurt", "amount": 1.25, "unit": "cups"}, {"item": "Fresh Ginger-Garlic Paste", "amount": 3, "unit": "tbsp"}, {"item": "Kewra Water & Rose Water", "amount": 1, "unit": "tsp each"}, {"item": "Pure Saffron Strands soaked in Warm Milk", "amount": 1, "unit": "pinch + 0.33 cup milk"}, {"item": "Desi Ghee", "amount": 0.33, "unit": "cup"}, {"item": "Fresh Mint & Cilantro Leaves", "amount": 1, "unit": "cup each", "notes": "Coarsely chopped"}, {"item": "Whole Spices (Green Cardamom, Cloves, Star Anise, Black Cardamom, Shahi Jeera, Cinnamon)", "amount": 2, "unit": "tbsp combined"}, {"item": "Raw Green Papaya Paste (Meat Tenderizer)", "amount": 1.5, "unit": "tbsp"}, {"item": "Wheat Flour Dough", "amount": 1, "unit": "ball", "notes": "For hermetic pot rim sealing"}]',
    '[{"step": 1, "title": "Royal Mutton Marination (Kacchi Akhni)", "instruction": "Marinate mutton with yogurt, ginger-garlic paste, papaya paste, half the fried onions, mint, cilantro, red chili powder, shahi jeera, garam masala, ghee, and salt. Refrigerate for at least 3 hours to break down collagen fibers."}, {"step": 2, "title": "70% Rice Par-Boil (Al Dente Basmati)", "instruction": "In a massive stockpot with 5 liters of heavily salted boiling water (infused with green cardamom, cinnamon, and bay leaf), boil soaked basmati rice for precisely 5-6 minutes until 70% cooked (grain bends slightly but does not snap). Drain immediately."}, {"step": 3, "title": "The Dum Layering Architecture", "instruction": "In a heavy-bottomed copper or cast-iron handi, spread the marinated mutton evenly as the bottom base. Layer the fragrant steaming basmati over the meat. Top with remaining golden onions, fresh mint, cilantro, warm saffron milk, kewra water, and swirls of melted desi ghee."}, {"step": 4, "title": "Hermetic Flour Dough Seal (Dum Pukht)", "instruction": "Roll wheat dough into a thick rope along the rim of the pot. Press lid down firmly to lock all internal steam pressure. Cook on medium flame for 15 minutes, then place a flat cast iron tawa underneath and slow-steam on low flame for 40 minutes."}, {"step": 5, "title": "Rest & Royal Reveal", "instruction": "Turn off flame and let rest for 15 minutes. Slice through the crisp dough seal. Use a flat saucer or skimmer to gently lift layers from bottom to top, revealing gradient hues of saffron, pure white basmati, and succulent spiced mutton. Serve with chilled cucumber-mint raita and mirchi ka salan."}]',
    '{"calories": 670, "protein": "42g", "carbs": "76g", "fat": "22g", "fiber": "4g"}', 5.0, 640, 'Ustad Khursheed & Ultimatum Test Kitchen'),

    ('rec-014', 'authentic-szechuan-kung-pao-chicken', 'Traditional Szechuan Kung Pao Chicken with Roasted Peanuts & Facing-Heaven Chilies', 'Fiery, sweet, tart, and mouth-numbing (Málà). Diced velvety chicken thighs wok-charred with authentic Szechuan peppercorns, dried facing-heaven chilies, crisp leek batons, and crunchy roasted peanuts in a complex dark Chinkiang vinegar glaze.', 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1200&q=80', 20, 10, 4, 460, 'Asian & Stir-Fry', 'Chinese', '["Chinese Cuisine", "Szechuan", "Wok Stir-Fry", "Spicy"]', '["High Protein", "Quick Dinner", "Spicy"]',
    '[{"item": "Boneless Skinless Chicken Thighs", "amount": 1.5, "unit": "lbs", "notes": "Diced into neat 3/4-inch cubes"}, {"item": "Shaoxing Cooking Wine", "amount": 2, "unit": "tbsp"}, {"item": "Light Soy Sauce & Dark Soy Sauce", "amount": 1.5, "unit": "tbsp each"}, {"item": "Cornstarch (for velveting & sauce)", "amount": 2, "unit": "tbsp"}, {"item": "Authentic Red Szechuan Peppercorns", "amount": 1, "unit": "tbsp", "notes": "Lightly crushed and deseeded"}, {"item": "Dried Facing-Heaven / Tien Tsin Chilies", "amount": 15, "unit": "whole", "notes": "Snipped into halves, seeds shaken out"}, {"item": "Aged Chinkiang Black Vinegar", "amount": 2, "unit": "tbsp"}, {"item": "Raw Sugar or Brown Sugar", "amount": 1.5, "unit": "tbsp"}, {"item": "Chicken Bone Broth", "amount": 0.25, "unit": "cup"}, {"item": "Scallions / Leeks", "amount": 4, "unit": "stalks", "notes": "Cut into 1-inch white batons"}, {"item": "Fresh Garlic & Ginger", "amount": 4, "unit": "cloves + 1 inch knob", "notes": "Thinly sliced into coins"}, {"item": "Roasted Unsalted Peanuts", "amount": 0.5, "unit": "cup", "notes": "Crisp and skins removed"}, {"item": "Peanut Oil or Neutral Oil", "amount": 3, "unit": "tbsp"}]',
    '[{"step": 1, "title": "Velvet the Chicken Cubes", "instruction": "In a bowl, toss diced chicken with 1 tbsp Shaoxing wine, 1 tbsp light soy sauce, 1 tbsp cornstarch, 1 tbsp water, and 1 tsp oil. Let sit for 15 minutes to create an insulating velvet protein seal."}, {"step": 2, "title": "Whisk the Master Sweet-Sour-Salty Glaze", "instruction": "In a small bowl, whisk Chinkiang black vinegar, sugar, dark soy sauce, remaining Shaoxing wine, chicken broth, and 1 tsp cornstarch until sugar dissolves completely."}, {"step": 3, "title": "Season the Wok & Bloom Aromatics", "instruction": "Heat a carbon-steel wok over maximum high flame until smoking hot. Add peanut oil, drop in Szechuan peppercorns and dried chilies. Stir-fry for 15 seconds until chilies darken to deep mahogany and oil is fragrant (do not burn)."}, {"step": 4, "title": "Flash Stir-Fry Chicken (Wok Hei)", "instruction": "Slide in chicken cubes and spread across the blazing wok surface. Sear for 90 seconds, then toss rapidly. Add sliced garlic, ginger, and scallion white batons; stir-fry for another 60 seconds."}, {"step": 5, "title": "Glaze & Peanut Finish", "instruction": "Pour the stirred master sauce around the perimeter of the wok. Toss vigorously as the sauce instantly thickens and coats every chicken cube in a glossy lacquer. Toss in roasted peanuts, give two swift wok flips, and serve immediately with jasmine rice."}]',
    '{"calories": 460, "protein": "36g", "carbs": "18g", "fat": "26g", "fiber": "4g"}', 4.94, 376, 'Chef Lin Wei & Ultimatum Test Kitchen'),

    ('rec-015', 'cantonese-dim-sum-ginger-scallion-dumplings', 'Artisanal Cantonese Dim Sum Ginger-Scallion Chicken & Shrimp Dumplings', 'Delicate translucent pleated dumplings packed with juicy minced chicken, wild tiger shrimp chunks, water chestnuts, toasted sesame oil, and fragrant scallion-ginger oil. Served with homemade chili crisp and black vinegar dip.', 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=1200&q=80', 35, 10, 4, 390, 'Asian & Stir-Fry', 'Chinese', '["Chinese Cuisine", "Dim Sum", "Cantonese", "Dumplings", "Appetizer"]', '["High Protein", "Comfort Food", "Crowd Pleaser"]',
    '[{"item": "Ground Chicken Thigh or Pork", "amount": 1, "unit": "lb"}, {"item": "Raw Tiger Shrimp", "amount": 0.5, "unit": "lb", "notes": "Peeled, deveined, and coarsely diced into chunks"}, {"item": "Round Dumpling / Gyoza Wrappers", "amount": 32, "unit": "wrappers", "notes": "Fresh thin wheat wrappers"}, {"item": "Fresh Water Chestnuts", "amount": 0.5, "unit": "cup", "notes": "Finely minced for crunch"}, {"item": "Scallions / Spring Onions", "amount": 4, "unit": "stalks", "notes": "Finely minced"}, {"item": "Fresh Ginger", "amount": 1.5, "unit": "tbsp", "notes": "Grated to fine paste"}, {"item": "Toasted Sesame Oil", "amount": 1.5, "unit": "tbsp"}, {"item": "Shaoxing Wine & Light Soy Sauce", "amount": 1, "unit": "tbsp each"}, {"item": "White Pepper & Sugar", "amount": 0.5, "unit": "tsp each"}, {"item": "Chili Crisp Oil & Chinkiang Vinegar", "amount": 3, "unit": "tbsp each", "notes": "For dipping sauce"}]',
    '[{"step": 1, "title": "Whip the Springy Dumpling Filling", "instruction": "In a large bowl, combine minced chicken, shrimp chunks, water chestnuts, ginger, scallions, soy sauce, Shaoxing wine, sesame oil, white pepper, salt, and cornstarch. Stir vigorously in one circular direction for 3 minutes until paste becomes cohesive and springy."}, {"step": 2, "title": "Pleat & Fold Dumplings", "instruction": "Place a wrapper on your palm. Add 1 tbsp filling to center. Moisten edges with a fingertip of water. Fold wrapper in half and create 5-6 tight overlapping pleats along one side to seal completely with zero air bubbles."}, {"step": 3, "title": "Bamboo Steamer Setup", "instruction": "Line bamboo steamer baskets with perforated parchment paper or napa cabbage leaves. Arrange dumplings with 1/2 inch gap between them."}, {"step": 4, "title": "High-Steam Cooking", "instruction": "Bring water in a wok to a vigorous rolling boil. Place stacked bamboo steamers on top. Cover tightly and steam over high heat for precisely 8-9 minutes until wrappers turn glossy and translucent."}, {"step": 5, "title": "Dipping Sauce & Presentation", "instruction": "Whisk chili crisp oil with Chinkiang black vinegar and minced scallions. Serve dumplings piping hot straight from the bamboo basket."}]',
    '{"calories": 390, "protein": "28g", "carbs": "38g", "fat": "12g", "fiber": "3g"}', 4.96, 420, 'Master Dim Sum Chef Chen & Ultimatum Test Kitchen');

-- 6. REVIEWS
INSERT INTO `reviews` (`id`, `slug`, `product_name`, `category`, `rating`, `summary`, `verdict`, `pros`, `cons`, `specifications`, `affiliate_link`, `affiliate_retailer`, `hero_image_url`, `author`)
VALUES
    ('rev-001', 'apex-chrono-v2-modular-smartwatch', 'Apex Chrono V2 Modular Smartwatch', 'tech_hardware', 4.8, 'A revolutionary titanium-chassis smartwatch featuring swappable sensor modules, 14-day battery life, and an ultra-bright 2000-nit AMOLED display engineered for extreme gamers and outdoor adventurers.', 'The Apex Chrono V2 is undeniably the most versatile and durable wearable we have tested this year. The modular magnetic sensor system solves the upgrade dilemma, offering unmatched build quality.',
    '["Hot-swappable sensor modules (Heart rate, GPS, EMG muscle tracker)", "Astonishing 14-day real-world battery endurance", "Aircraft-grade Grade 5 Titanium bezel with sapphire crystal", "Ultra-responsive 120Hz 2000-nit AMOLED panel"]',
    '["Proprietary charging puck required", "Heavier on smaller wrists (68g without strap)", "Companion app setup takes 15 minutes"]',
    '{"Display": "1.43-inch AMOLED, 466x466 (2000 nits peak)", "Case Material": "Grade 5 Brushed Titanium & Ceramic Back", "Battery Capacity": "620 mAh (Up to 14 Days Normal Usage)", "Water Resistance": "10 ATM (100m Submersion Certified)", "Connectivity": "Bluetooth 5.4, Wi-Fi 6, Dual-Frequency Multi-GNSS", "Weight": "68 grams (Chassis only)", "OS Compatibility": "iOS 16+ & Android 12+", "MSRP": "$449.00 USD"}',
    'https://example.com/affiliate/apex-chrono-v2', 'Apex Official Store / Amazon Prime', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80', 'Alex Mercer (Hardware Lead)'),

    ('rev-002', 'tokyo-ramen-box-express-delivery', 'Tokyo Craft Ramen Express Kit (10-Bowl Artisanal Box)', 'food_lifestyle', 4.9, 'A flash-frozen Michelin-grade artisanal ramen delivery kit direct from Tokyo master kitchens, featuring 24-hour simmered Tonkotsu & Black Garlic broths, handmade alkaline noodles, and melt-in-your-mouth Chashu pork belly.', 'This is not instant ramen—it is bona fide restaurant broth delivered right to your doorstep. The freshness and depth of umami will ruin takeout ramen forever.',
    '["Gel-pack frozen rich broth pouches preserved without preservatives", "Incredible springy texture in the freshly extruded wavy noodles", "Includes authentic marinated ajitsuke tamago eggs & wood ear mushrooms", "Ready in under 8 minutes from freezer to table"]',
    '["Requires significant freezer storage space", "Higher shipping cost outside metropolitan delivery zones"]',
    '{"Portion Count": "10 Complete Bowls (5 Tonkotsu, 5 Spicy Miso)", "Shelf Life": "6 Months Frozen (-18°C)", "Prep Time": "8 Minutes (Boil & Combine)", "Included Toppings": "Torched Chashu, Seasoned Menma, Nori, Rayu Chili Oil", "Delivery Speed": "Overnight Insulated Dry Ice Express", "Price Per Bowl": "$12.90 ($129 Box Total)"}',
    'https://example.com/affiliate/tokyo-ramen-box', 'Tokyo Gourmet Direct', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80', 'Chef Marco Bellini');

-- 7. ARTICLES
INSERT INTO `articles` (`id`, `slug`, `title`, `subtitle`, `category`, `hero_image_url`, `gallery_images`, `content`, `tags`, `author`, `read_time`, `is_breaking`, `shoppable_items`)
VALUES
    ('art-001', 'cyberpunk-techwear-modular-shells-2026', 'Cyberpunk Techwear 2026: Rainproof Modular Shells, Magnetic Fidlock & Urban Stealth', 'From 3-layer Gore-Tex Pro membranes to hot-swappable magnetic cargo systems, we test the best technical apparel for digital nomads and gamers.', 'beauty_fashion', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    '["https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80"]',
    '# The Convergence of Streetwear and Functional Ergonomics\n\nModern lifestyle fashion has evolved far beyond superficial branding. In 2026, Techwear combines military-grade water repellency, magnetic quick-release fasteners, and breathable membranes engineered for maximum mobility.\n\n### Key Materials & Thermal Profiling\n- Gore-Tex Pro 3-Layer Laminate: Offers unmatched 28,000mm hydrostatic head water resistance while allowing vapor sweat perspiration to escape freely.\n- Fidlock V-Buckle Fasteners: German-engineered neodymium magnetic closures that snap shut automatically under high tension.\n- Schoeller Dryskin 4-Way Stretch: Abrasion-resistant ballistic nylon blend that repels street grime and rain splatters.',
    '["Techwear", "Modular Fashion", "Streetwear", "Apparel Teardown"]', 'Elena Vance (Style & Materials Architect)', 6, 0,
    '[{"name": "AcroPulse Modular Storm Shell J1", "brand": "AcroPulse Design Labs", "price": "$480.00", "affiliate_url": "https://example.com/shop/acropulse-shell", "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=400&q=80"}, {"name": "Fidlock Magnetic Utility Rig V2", "brand": "Fidlock Hardware", "price": "$120.00", "affiliate_url": "https://example.com/shop/fidlock-rig", "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=400&q=80"}]'),

    ('art-002', 'gamer-skincare-blue-light-barrier-science', 'Blue Light Barrier Science: Active Peptides, Ceramides & Skincare for High-Screen Demographics', '10+ hours in front of OLED monitors causes oxidative barrier fatigue. Here is the scientific dermatological protocol to restore hydration and collagen integrity.', 'beauty_fashion', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80',
    '["https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80"]',
    '# Understanding High-Energy Visible (HEV) Blue Light Skin Stress\n\nProlonged exposure to 400-500nm high-energy visible light from monitors and mobile displays produces reactive oxygen species (ROS) that degrade skin elastin and barrier lipids.\n\n### The 3-Step Evidence-Based Routine\n1. Copper Tripeptide-1 Serum (GHK-Cu): Stimulates dermal matrix synthesis and soothes inflammation.\n2. 5-Ceramide NP Complex Moisturizer: Rebuilds intercellular lipid mortar, locking in 98% of trans-epidermal water.\n3. Ectoin & Lutein Antioxidant Mist: Shields cellular structures from screen oxidation.',
    '["Skincare Science", "Dermatology", "Blue Light Protection", "Grooming"]', 'Dr. Sarah Lin (Dermatological Chemistry)', 5, 0,
    '[{"name": "GHK-Cu Pure Copper Peptide Serum", "brand": "BioCellular Labs", "price": "$68.00", "affiliate_url": "https://example.com/shop/copper-peptide", "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=400&q=80"}]'),

    ('art-003', 'next-gen-portable-handhelds-oled-showdown', 'Next-Gen Portable Handhelds: APU Thermal Benchmarks & 144Hz OLED Showdown', 'We put the latest Zen 5 handheld compute blades through 200 hours of frame-time testing, battery curve profiling, and VRR latency benchmarks.', 'gaming_news', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    '["https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=800&q=80"]',
    '# The Handheld Renaissance: Zen 5 RDNA 3.5 Silicon Analyzed\n\nPortable PC gaming has reached a historic inflection point. With 15W TDP envelopes now capable of sustained 1080p 60FPS gaming in AAA titles, the hardware engineering inside modern handhelds is astonishing.',
    '["Gaming News", "Handhelds", "Hardware Benchmarks", "OLED"]', 'Alex Mercer (Hardware Lead)', 7, 1, '[]'),

    ('art-004', 'ultimatum-summer-championship-2026-announcement', 'Ultimatum Summer Arcade Championship 2026: $10,000 Prize Pool & Double XP Announced', 'Six weeks of global weekly reset leaderboards, sponsored gear bounties from Razer and Anker, and limited-edition profile badges.', 'news_editorial', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    '[]',
    '# The Biggest Web Arcade Tournament in Platform History\n\nStarting this weekend, The Arcade will host the official 2026 Summer Tournament.\n\n### Tournament Highlights\n- Weekly Score Resets: Resetting every Sunday midnight UTC.\n- Anti-Cheat Verification: Real-time score validation.\n- Engagement XP Multipliers: Earn 2x XP for all high-score submissions!',
    '["Tournaments", "Double XP", "Esports", "Community"]', 'Devon Wright (Arcade Lead)', 4, 1, '[]');

-- 8. SPONSORS
INSERT INTO `sponsors` (`id`, `sponsor_name`, `image_url`, `destination_url`, `slot_position`, `impressions_tracked`, `clicks_tracked`, `is_active`)
VALUES
    ('sp-001', 'Razer Blade Pro Series', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80', 'https://example.com/sponsor/razer', 'header_banner', 48200, 2840, 1),
    ('sp-002', 'Hestan NanoBond Master Cookware', 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80', 'https://example.com/sponsor/hestan', 'sidebar', 31400, 1620, 1),
    ('sp-003', 'Anker Prime GaN Fast Chargers', 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80', 'https://example.com/sponsor/anker', 'in_content', 64100, 4290, 1),
    ('sp-004', 'NordVPN Cyber Security', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80', 'https://example.com/sponsor/nordvpn', 'footer', 18900, 940, 1);

-- 9. CUSTOM PAGES
INSERT INTO `pages` (`id`, `slug`, `title`, `subtitle`, `content`, `meta_description`, `show_in_nav`, `show_in_footer`, `enable_ads`)
VALUES
    ('page-001', 'summer-championship-2026', 'Ultimatum Summer Arcade Championship 2026', 'Compete for $10,000 in gear prizes, exclusive limited-edition gamer badges, and global bragging rights.',
    '# Welcome to the Summer 2026 Arcade Championship!\n\nGet ready for 6 weeks of intense high-score competition across The Arcade.\n\n### Tournament Rules & Mechanics\n1. Weekly Leaderboard Resets: Every Sunday at midnight UTC, the top 10 players on Neon Asteroid Blitz receive tournament bonus tokens.\n2. Double Engagement Points: Earn 2x XP for every 1,000 points scored in canvas games during tournament hours.\n3. Anti-Cheat Verification: All scores are monitored in real-time by our Admin Moderation engine.',
    'Join the Ultimatum Summer 2026 Arcade Tournament! Play weekly retro games, score points, and win top tier sponsor gear.', 1, 1, 1);

-- 10. LEADERBOARDS
INSERT INTO `leaderboards` (`id`, `user_id`, `game_id`, `score`)
VALUES
    ('lb-001', 'user-001', 'game-001', 18450),
    ('lb-002', 'user-002', 'game-001', 15200),
    ('lb-003', 'user-003', 'game-001', 12900),
    ('lb-005', 'user-003', 'game-002', 24800),
    ('lb-006', 'user-001', 'game-002', 19500),
    ('lb-007', 'user-004', 'game-003', 9600),
    ('lb-008', 'user-002', 'game-003', 7850),
    ('lb-009', 'user-001', 'game-004', 14200),
    ('lb-010', 'user-003', 'game-004', 11900);

-- 11. SITE SETTINGS
INSERT INTO `site_settings` (`key`, `value`)
VALUES ('main_settings', '{"announcement": {"enabled": true, "text": "🔥 ULTIMATUM ARCADE TOURNAMENT: Double XP Weekend is LIVE! Play & Claim Badges", "link": "/games"}, "monetization": {"ads_enabled": true, "header_ad": true, "sidebar_ad": true, "in_content_ad": true, "sticky_footer_ad": true, "rewarded_ads": true}, "maintenance_mode": false}');

-- 12. Re-enable Foreign Key Checks
SET FOREIGN_KEY_CHECKS = 1;
